include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart ]

linter:

  rules:
    # Just for demo
    avoid_print: false

    use_enums: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_function_type_syntax_for_parameters: true

    use_super_parameters: true
    use_decorated_box: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_init_to_null: true
    # authorise build(_)
    avoid_renaming_method_parameters: false

    curly_braces_in_flow_control_structures: false
    comment_references: true
    no_adjacent_strings_in_list: true
    always_put_required_named_parameters_first: false
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_multiple_declarations_per_line: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_void_async: true
    cascade_invocations: true
    directives_ordering: true
    flutter_style_todos: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    one_member_abstracts: true
    prefer_expression_function_bodies: true

    unnecessary_lambdas: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options